[[constraint]]
  branch = "master"
  name = "github.com/egjiri/go-kit"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.6.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.1.1"

[prune]
  go-tests = true
  unused-packages = true
